import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
    MzInputModule,
    MzCheckboxModule,
    MzRadioButtonModule,
    MzValidationModule,
    MzTimepickerModule,
    MzIconMdiModule,
    MzIconModule,
    MzSidenavModule,
    MzNavbarModule,
    MzTextareaModule,
    MzDatepickerModule,
    MzSelectModule,
    MzCollapsibleModule,
    MzButtonModule,
    MzModalModule,
    MzTooltipModule,
    MzSpinnerModule,
    MzToastModule,
    MzProgressModule,
    MzTabModule,
    MzFeatureDiscoveryModule,
    MzSwitchModule
} from 'ng2-materialize';

@NgModule({
    imports: [
        MzInputModule,
        MzCheckboxModule,
        MzRadioButtonModule,
        MzValidationModule,
        MzTimepickerModule,
        MzNavbarModule,
        MzSidenavModule,
        MzIconModule,
        MzIconMdiModule,
        MzTextareaModule,
        MzDatepickerModule,
        MzSelectModule,
        MzCollapsibleModule,
        MzButtonModule,
        MzModalModule,
        MzTooltipModule,
        MzSpinnerModule,
        MzToastModule,
        MzProgressModule,
        MzTabModule,
        MzFeatureDiscoveryModule,
        MzSwitchModule
    ],
    exports: [
        MzInputModule,
        MzCheckboxModule,
        MzRadioButtonModule,
        MzValidationModule,
        MzTimepickerModule,
        MzNavbarModule,
        MzSidenavModule,
        MzIconModule,
        MzIconMdiModule,
        MzTextareaModule,
        MzDatepickerModule,
        MzSelectModule,
        MzCollapsibleModule,
        MzButtonModule,
        MzModalModule,
        MzTooltipModule,
        MzSpinnerModule,
        MzToastModule,
        MzProgressModule,
        MzTabModule,
        MzFeatureDiscoveryModule,
        MzSwitchModule
    ]
})
export class MaterialModule { }
